### ISSUE TITLE
this node cause lora folder not foldable.....

### ISSUE THREAD

**Issue by KumaPlayWithShader** [catscandrive/comfyui-imagesubfolders#1]
This image node cause lora node's subfolder not foldable
And the subfolder for image  does not work well, too
(no preview image in node, now)

lora node  have better folder structure .which only show all subfolder name , 
hide all sub object
Now it's gone.  
I  have a lot of models in a long list, now. 
UI not clean and simple anymore. 

I dont's want to see a hundred object  list liks this
subfolder1/01
....
subfolder1/99
subfolder2/01
....
subfolder2/99
subfolder3/01
....
subfolder3/99

It's painful to scrolling an extreme long list to find an object......
the old lora subfolder just show subfolder1 subfolder2 subfolder3

I can not remove this by disable it , it change something in comfyUI
I  try to disable this  comfyui-imagesubfolders,
 but  my lora subfolder does not get back.
pls , fixed it

**Comment by KumaPlayWithShader** [comment]
The Old Lora node's SubFolder works so  well  like this ,keep  simple and clean
https://i.imgur.com/PuqyEar.jpeg

But now it's broken cause I install this node
https://i.imgur.com/ynsttkN.jpeg

I really need to get back the old  folder style....Can you help??
I uninstall your image node but Lora node still broken

**Comment by catscandrive** [comment]
Default lora loader has always worked this way for me:

![image](https://github.com/catscandrive/comfyui-imagesubfolders/assets/10904002/5376b0bd-8b0d-4e06-ae28-fc9a42c8fbd6)

Long list of all the loras with a subfolder at the front.

pyssssss lora loader has nice nested subfolders.  maybe you are/were using it?

![image](https://github.com/catscandrive/comfyui-imagesubfolders/assets/10904002/60e0c345-3323-46ca-a6ab-a76fc028534f)

https://github.com/pythongosssss/ComfyUI-Custom-Scripts

Either way I don't see how this node could break other nodes as it's not changing anything.

**Comment by KumaPlayWithShader** [comment]
I figure out the Lora subFolder problem  come from  "ComfyUI-Custom-Scripts"
If I remove it ,  "Load Lora" nested subfolder works again,

I'm not sure why my "Load Lora" has  nested subfolder 
But I'm not use the "Lora Loader " node from other custom script

Maybe there is a conflict between custom node.
